version: '2'
services:
  web:
    image: 053116275671.dkr.ecr.us-west-1.amazonaws.com/divination-software/server:latest
    cpu_shares: 10
    mem_limit: 300288000
    ports:
    - "80:8080"
    - "443:443"
    links:
    - mongo
  mongo:
    image: mongo:3
    cpu_shares: 10
    mem_limit: 200288000
