version: '2'
services:
  web:
    image: divination-software/server:dev
    networks:
      - staging-network
    ports:
      - "8080:8080"
  mongo:
    image: mongo:3
    networks:
      - staging-network
  sim:
    image: divination-software/sim:dev
    ports:
      - "8443:8443"
    networks:
      - staging-network
networks:
  staging-network:
    driver: bridge
